import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import People from "./people/Details";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JS FRAMEWORKS CA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <ul className={styles.navigation}>
          <li>
            <Link href="/">
              <a>Home</a>
            </Link>
          </li>
          <li>
            <Link href="/Login">
              <a>Login</a>
            </Link>
          </li>
          <li>
            <Link href="/Contact">
              <a>Contact</a>
            </Link>
          </li>
        </ul>
      </nav>
      <hr />

      <main className={styles.main}>
        <People />
      </main>
    </div>
  );
}
